version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/sters/markdown-table-formatter
    steps:
      - checkout
      - run: make ci
      - run: bash <$(shell curl -s https://codecov.io/bash)